- name: Install apache2 package
  apt:
    name: apache2
    state: present
  become: true
- name: Start apache2
  service:
    name: apache2
    state: started
    enabled: true
  become: true

- name: Open port for HTTP
  firewalld:
    service: http
    permanent: true
    state: enabled
  become: true

- name: Restart firewalld
  service:
    name: firewalld
    state: reloaded
  become: true

